workspace:
  base: /go
  path: src/github.com/uswitch/kiam

pipeline:
  test:
    secrets: [ codecov_token ]
    image: golang:1.12
    environment:
      GO111MODULE: "on"
    commands:
      - make test
      - make coverage.txt
      - ./ci/codecov.sh

  benchmarks:
    image: golang:1.12
    environment:
      GO111MODULE: "on"
    commands:
      - make bench

  docker:
    when:
      event: push
    image: plugins/docker
    registry: quay.io
    repo: quay.io/uswitch/kiam
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}

  docker-tagged:
    when:
      event: tag
    image: plugins/docker
    repo: quay.io/uswitch/kiam
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}

  helm-package:
    image: alpine/helm:2.14.3
    environment:
      APP: kiam
      REPO: github.com/uswitch/kiam-helm-charts.git
    secrets: [ ci_user, ci_token, ci_email ]
    commands:
      sh ci/helm-package.sh
    when:
      event: push
      branch: master
