workspace:
  base: /go
  path: src/github.com/uswitch/kiam

pipeline:
  test:
    image: golang:1.10
    commands:
      - go test test/unit/*_test.go
      - go test test/functional/*_test.go

  benchmarks:
    image: golang:1.10
    commands:
      - go test -run=XX -bench=. test/unit/*.go

  build:
    image: golang:1.10
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/kiam cmd/kiam/*.go

  docker:
    when:
      event: push
    image: plugins/docker
    registry: quay.io
    repo: quay.io/uswitch/kiam
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}

  docker-tagged:
    when:
      event: tag
    image: plugins/docker
    repo: quay.io/uswitch/kiam
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
