apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam
spec:
  template:
    metadata:
      labels:
        app: kiam
    spec:
      hostNetwork: true
      volumes:
        - name: ssl-certs
          hostPath:
            path: /usr/share/ca-certificates
      containers:
        - name: kiam
          securityContext:
            privileged: true
          image: uswitch/kiam:latest
          command: ["/kiam"]
          args:
            - --iptables
            - --host-interface=cali+
            - --role-base-arn=arn:aws:iam::1234567890:role/
            - --json-log
            - --port=8181
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs