// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package kiam

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPodRoleRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPodRoleRequest) Reset()         { *m = GetPodRoleRequest{} }
func (m *GetPodRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetPodRoleRequest) ProtoMessage()    {}
func (*GetPodRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{0}
}
func (m *GetPodRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodRoleRequest.Unmarshal(m, b)
}
func (m *GetPodRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodRoleRequest.Marshal(b, m, deterministic)
}
func (dst *GetPodRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodRoleRequest.Merge(dst, src)
}
func (m *GetPodRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetPodRoleRequest.Size(m)
}
func (m *GetPodRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodRoleRequest proto.InternalMessageInfo

func (m *GetPodRoleRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{1}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRoleCredentialsRequest struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ServiceAccountToken  string   `protobuf:"bytes,2,opt,name=service_account_token,json=serviceAccountToken,proto3" json:"service_account_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleCredentialsRequest) Reset()         { *m = GetRoleCredentialsRequest{} }
func (m *GetRoleCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoleCredentialsRequest) ProtoMessage()    {}
func (*GetRoleCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{2}
}
func (m *GetRoleCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleCredentialsRequest.Unmarshal(m, b)
}
func (m *GetRoleCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleCredentialsRequest.Marshal(b, m, deterministic)
}
func (dst *GetRoleCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleCredentialsRequest.Merge(dst, src)
}
func (m *GetRoleCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoleCredentialsRequest.Size(m)
}
func (m *GetRoleCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleCredentialsRequest proto.InternalMessageInfo

func (m *GetRoleCredentialsRequest) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *GetRoleCredentialsRequest) GetServiceAccountToken() string {
	if m != nil {
		return m.ServiceAccountToken
	}
	return ""
}

type Credentials struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AccessKeyId          string   `protobuf:"bytes,3,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey      string   `protobuf:"bytes,4,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Expiration           string   `protobuf:"bytes,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	LastUpdated          string   `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{3}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Credentials) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Credentials) GetAccessKeyId() string {
	if m != nil {
		return m.AccessKeyId
	}
	return ""
}

func (m *Credentials) GetSecretAccessKey() string {
	if m != nil {
		return m.SecretAccessKey
	}
	return ""
}

func (m *Credentials) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Credentials) GetExpiration() string {
	if m != nil {
		return m.Expiration
	}
	return ""
}

func (m *Credentials) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type GetHealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthRequest) Reset()         { *m = GetHealthRequest{} }
func (m *GetHealthRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthRequest) ProtoMessage()    {}
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{4}
}
func (m *GetHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthRequest.Unmarshal(m, b)
}
func (m *GetHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthRequest.Marshal(b, m, deterministic)
}
func (dst *GetHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthRequest.Merge(dst, src)
}
func (m *GetHealthRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthRequest.Size(m)
}
func (m *GetHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthRequest proto.InternalMessageInfo

type HealthStatus struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthStatus) Reset()         { *m = HealthStatus{} }
func (m *HealthStatus) String() string { return proto.CompactTextString(m) }
func (*HealthStatus) ProtoMessage()    {}
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{5}
}
func (m *HealthStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthStatus.Unmarshal(m, b)
}
func (m *HealthStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthStatus.Marshal(b, m, deterministic)
}
func (dst *HealthStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthStatus.Merge(dst, src)
}
func (m *HealthStatus) XXX_Size() int {
	return xxx_messageInfo_HealthStatus.Size(m)
}
func (m *HealthStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HealthStatus proto.InternalMessageInfo

func (m *HealthStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type IsAllowedAssumeRoleRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Role                 *Role    `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAllowedAssumeRoleRequest) Reset()         { *m = IsAllowedAssumeRoleRequest{} }
func (m *IsAllowedAssumeRoleRequest) String() string { return proto.CompactTextString(m) }
func (*IsAllowedAssumeRoleRequest) ProtoMessage()    {}
func (*IsAllowedAssumeRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{6}
}
func (m *IsAllowedAssumeRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedAssumeRoleRequest.Unmarshal(m, b)
}
func (m *IsAllowedAssumeRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedAssumeRoleRequest.Marshal(b, m, deterministic)
}
func (dst *IsAllowedAssumeRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedAssumeRoleRequest.Merge(dst, src)
}
func (m *IsAllowedAssumeRoleRequest) XXX_Size() int {
	return xxx_messageInfo_IsAllowedAssumeRoleRequest.Size(m)
}
func (m *IsAllowedAssumeRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedAssumeRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedAssumeRoleRequest proto.InternalMessageInfo

func (m *IsAllowedAssumeRoleRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *IsAllowedAssumeRoleRequest) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type IsAllowedAssumeRoleResponse struct {
	Decision             *Decision `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IsAllowedAssumeRoleResponse) Reset()         { *m = IsAllowedAssumeRoleResponse{} }
func (m *IsAllowedAssumeRoleResponse) String() string { return proto.CompactTextString(m) }
func (*IsAllowedAssumeRoleResponse) ProtoMessage()    {}
func (*IsAllowedAssumeRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{7}
}
func (m *IsAllowedAssumeRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedAssumeRoleResponse.Unmarshal(m, b)
}
func (m *IsAllowedAssumeRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedAssumeRoleResponse.Marshal(b, m, deterministic)
}
func (dst *IsAllowedAssumeRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedAssumeRoleResponse.Merge(dst, src)
}
func (m *IsAllowedAssumeRoleResponse) XXX_Size() int {
	return xxx_messageInfo_IsAllowedAssumeRoleResponse.Size(m)
}
func (m *IsAllowedAssumeRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedAssumeRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedAssumeRoleResponse proto.InternalMessageInfo

func (m *IsAllowedAssumeRoleResponse) GetDecision() *Decision {
	if m != nil {
		return m.Decision
	}
	return nil
}

type Decision struct {
	IsAllowed            bool     `protobuf:"varint,1,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
	Explanation          string   `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Decision) Reset()         { *m = Decision{} }
func (m *Decision) String() string { return proto.CompactTextString(m) }
func (*Decision) ProtoMessage()    {}
func (*Decision) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2e69afb80b2d2881, []int{8}
}
func (m *Decision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Decision.Unmarshal(m, b)
}
func (m *Decision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Decision.Marshal(b, m, deterministic)
}
func (dst *Decision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Decision.Merge(dst, src)
}
func (m *Decision) XXX_Size() int {
	return xxx_messageInfo_Decision.Size(m)
}
func (m *Decision) XXX_DiscardUnknown() {
	xxx_messageInfo_Decision.DiscardUnknown(m)
}

var xxx_messageInfo_Decision proto.InternalMessageInfo

func (m *Decision) GetIsAllowed() bool {
	if m != nil {
		return m.IsAllowed
	}
	return false
}

func (m *Decision) GetExplanation() string {
	if m != nil {
		return m.Explanation
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPodRoleRequest)(nil), "kiam.GetPodRoleRequest")
	proto.RegisterType((*Role)(nil), "kiam.Role")
	proto.RegisterType((*GetRoleCredentialsRequest)(nil), "kiam.GetRoleCredentialsRequest")
	proto.RegisterType((*Credentials)(nil), "kiam.Credentials")
	proto.RegisterType((*GetHealthRequest)(nil), "kiam.GetHealthRequest")
	proto.RegisterType((*HealthStatus)(nil), "kiam.HealthStatus")
	proto.RegisterType((*IsAllowedAssumeRoleRequest)(nil), "kiam.IsAllowedAssumeRoleRequest")
	proto.RegisterType((*IsAllowedAssumeRoleResponse)(nil), "kiam.IsAllowedAssumeRoleResponse")
	proto.RegisterType((*Decision)(nil), "kiam.Decision")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KiamServiceClient is the client API for KiamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KiamServiceClient interface {
	GetPodRole(ctx context.Context, in *GetPodRoleRequest, opts ...grpc.CallOption) (*Role, error)
	GetRoleCredentials(ctx context.Context, in *GetRoleCredentialsRequest, opts ...grpc.CallOption) (*Credentials, error)
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*HealthStatus, error)
	IsAllowedAssumeRole(ctx context.Context, in *IsAllowedAssumeRoleRequest, opts ...grpc.CallOption) (*IsAllowedAssumeRoleResponse, error)
}

type kiamServiceClient struct {
	cc *grpc.ClientConn
}

func NewKiamServiceClient(cc *grpc.ClientConn) KiamServiceClient {
	return &kiamServiceClient{cc}
}

func (c *kiamServiceClient) GetPodRole(ctx context.Context, in *GetPodRoleRequest, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/kiam.KiamService/GetPodRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiamServiceClient) GetRoleCredentials(ctx context.Context, in *GetRoleCredentialsRequest, opts ...grpc.CallOption) (*Credentials, error) {
	out := new(Credentials)
	err := c.cc.Invoke(ctx, "/kiam.KiamService/GetRoleCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiamServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*HealthStatus, error) {
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, "/kiam.KiamService/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kiamServiceClient) IsAllowedAssumeRole(ctx context.Context, in *IsAllowedAssumeRoleRequest, opts ...grpc.CallOption) (*IsAllowedAssumeRoleResponse, error) {
	out := new(IsAllowedAssumeRoleResponse)
	err := c.cc.Invoke(ctx, "/kiam.KiamService/IsAllowedAssumeRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KiamServiceServer is the server API for KiamService service.
type KiamServiceServer interface {
	GetPodRole(context.Context, *GetPodRoleRequest) (*Role, error)
	GetRoleCredentials(context.Context, *GetRoleCredentialsRequest) (*Credentials, error)
	GetHealth(context.Context, *GetHealthRequest) (*HealthStatus, error)
	IsAllowedAssumeRole(context.Context, *IsAllowedAssumeRoleRequest) (*IsAllowedAssumeRoleResponse, error)
}

func RegisterKiamServiceServer(s *grpc.Server, srv KiamServiceServer) {
	s.RegisterService(&_KiamService_serviceDesc, srv)
}

func _KiamService_GetPodRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiamServiceServer).GetPodRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiam.KiamService/GetPodRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiamServiceServer).GetPodRole(ctx, req.(*GetPodRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KiamService_GetRoleCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiamServiceServer).GetRoleCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiam.KiamService/GetRoleCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiamServiceServer).GetRoleCredentials(ctx, req.(*GetRoleCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KiamService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiamServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiam.KiamService/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiamServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KiamService_IsAllowedAssumeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAllowedAssumeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KiamServiceServer).IsAllowedAssumeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiam.KiamService/IsAllowedAssumeRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KiamServiceServer).IsAllowedAssumeRole(ctx, req.(*IsAllowedAssumeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KiamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kiam.KiamService",
	HandlerType: (*KiamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPodRole",
			Handler:    _KiamService_GetPodRole_Handler,
		},
		{
			MethodName: "GetRoleCredentials",
			Handler:    _KiamService_GetRoleCredentials_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _KiamService_GetHealth_Handler,
		},
		{
			MethodName: "IsAllowedAssumeRole",
			Handler:    _KiamService_IsAllowedAssumeRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_2e69afb80b2d2881) }

var fileDescriptor_service_2e69afb80b2d2881 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x93, 0x90, 0xb6, 0xc9, 0xa4, 0x2d, 0x64, 0xca, 0x1f, 0x63, 0x44, 0x49, 0x97, 0x4b,
	0xd5, 0x43, 0x0e, 0xe9, 0x89, 0x63, 0x04, 0x52, 0x08, 0xe1, 0x80, 0x52, 0xb8, 0x21, 0x59, 0x8b,
	0x3d, 0x82, 0x55, 0x6c, 0xaf, 0xf1, 0xae, 0xa1, 0x79, 0x22, 0xde, 0x8a, 0x67, 0x41, 0xde, 0xb1,
	0x5d, 0xa3, 0xa6, 0xbd, 0xad, 0xbf, 0xdf, 0xec, 0xcc, 0xec, 0x7c, 0x63, 0x38, 0x32, 0x94, 0xff,
	0x52, 0x21, 0x4d, 0xb3, 0x5c, 0x5b, 0x8d, 0xfd, 0x8d, 0x92, 0x89, 0x78, 0x0d, 0xe3, 0x05, 0xd9,
	0x4f, 0x3a, 0x5a, 0xeb, 0x98, 0xd6, 0xf4, 0xb3, 0x20, 0x63, 0xf1, 0x18, 0x7a, 0x2a, 0xf3, 0xba,
	0x93, 0xee, 0xf9, 0x70, 0xdd, 0x53, 0x99, 0xf0, 0xa1, 0x5f, 0x62, 0x44, 0xe8, 0xa7, 0x32, 0xa1,
	0x8a, 0xb8, 0xb3, 0xd0, 0xf0, 0x7c, 0x41, 0xb6, 0xc4, 0x6f, 0x73, 0x8a, 0x28, 0xb5, 0x4a, 0xc6,
	0xa6, 0x4e, 0x74, 0x0a, 0xfd, 0x5c, 0xc7, 0x7c, 0x61, 0x34, 0x83, 0x69, 0x59, 0x72, 0xea, 0x2a,
	0x39, 0x1d, 0x67, 0xf0, 0xa4, 0x6a, 0x2a, 0x90, 0x61, 0xa8, 0x8b, 0xd4, 0x06, 0x56, 0x6f, 0x28,
	0xf5, 0x7a, 0xae, 0xc2, 0x49, 0x05, 0xe7, 0xcc, 0x3e, 0x97, 0x48, 0xfc, 0xed, 0xc2, 0xa8, 0x55,
	0xaa, 0x6c, 0x2a, 0xd4, 0x51, 0xd3, 0x54, 0x79, 0x2e, 0x35, 0xbb, 0xcd, 0xa8, 0x4a, 0xe3, 0xce,
	0x28, 0xe0, 0x48, 0x86, 0x21, 0x19, 0x13, 0x6c, 0x68, 0x1b, 0xa8, 0xc8, 0x7b, 0xe0, 0xe0, 0x88,
	0xc5, 0x15, 0x6d, 0x97, 0x11, 0x5e, 0xc0, 0xd8, 0x50, 0x98, 0x93, 0x0d, 0x6e, 0x42, 0xbd, 0xbe,
	0x8b, 0x7b, 0xc8, 0x60, 0x5e, 0x47, 0xe3, 0x63, 0xd8, 0xe3, 0x5e, 0xf7, 0x1c, 0xe7, 0x0f, 0x3c,
	0x05, 0xa0, 0xeb, 0x4c, 0xe5, 0xd2, 0x2a, 0x9d, 0x7a, 0xfb, 0x0e, 0xb5, 0x14, 0x3c, 0x83, 0xc3,
	0x58, 0x1a, 0x1b, 0x14, 0x59, 0x24, 0x2d, 0x45, 0xde, 0x01, 0x37, 0x51, 0x6a, 0x5f, 0x58, 0x12,
	0x08, 0x8f, 0x16, 0x64, 0xdf, 0x93, 0x8c, 0xed, 0x8f, 0x6a, 0x90, 0xe2, 0x1c, 0x0e, 0x59, 0xb8,
	0xb2, 0xd2, 0x16, 0x06, 0x3d, 0x38, 0x48, 0xc8, 0x18, 0xf9, 0xbd, 0x7e, 0x77, 0xfd, 0x29, 0x3e,
	0x82, 0xbf, 0x34, 0xf3, 0x38, 0xd6, 0xbf, 0x29, 0x9a, 0x1b, 0x53, 0x24, 0x74, 0x8f, 0xb3, 0x8d,
	0x41, 0xbd, 0xdd, 0x06, 0x89, 0x25, 0xbc, 0xd8, 0x99, 0xcd, 0x64, 0x3a, 0x35, 0x84, 0x17, 0x30,
	0x88, 0x28, 0x54, 0xa6, 0x7c, 0x2b, 0x7b, 0x7c, 0xcc, 0x29, 0xde, 0x55, 0xea, 0xba, 0xe1, 0x62,
	0x05, 0x83, 0x5a, 0xc5, 0x97, 0x00, 0xca, 0x04, 0x92, 0xf3, 0xba, 0x9b, 0x83, 0xf5, 0x50, 0xd5,
	0x85, 0x70, 0x02, 0x23, 0xba, 0xce, 0x62, 0x99, 0xf2, 0x14, 0xd9, 0xc5, 0xb6, 0x34, 0xfb, 0xd3,
	0x83, 0xd1, 0x4a, 0xc9, 0xe4, 0x8a, 0x17, 0x04, 0x2f, 0x01, 0x6e, 0xd6, 0x18, 0x9f, 0x71, 0x13,
	0xb7, 0x16, 0xdb, 0x6f, 0x3d, 0x50, 0x74, 0xf0, 0x03, 0xe0, 0xed, 0xd5, 0xc5, 0x57, 0xcd, 0xe5,
	0xdd, 0x4b, 0xed, 0x8f, 0x39, 0xa0, 0x45, 0x44, 0x07, 0xdf, 0xc0, 0xb0, 0x31, 0x0d, 0x9f, 0x36,
	0x29, 0xfe, 0x73, 0xd1, 0x47, 0xd6, 0xdb, 0x4e, 0x8a, 0x0e, 0x7e, 0x85, 0x93, 0x1d, 0x33, 0xc6,
	0x09, 0x07, 0xdf, 0x6d, 0xa6, 0x7f, 0x76, 0x4f, 0x04, 0x1b, 0x24, 0x3a, 0xdf, 0xf6, 0xdd, 0xdf,
	0x7e, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x46, 0xb8, 0x53, 0x06, 0xfe, 0x03, 0x00, 0x00,
}
