{{- if .Values.server.enabled -}}
{{- if .Values.serviceAccounts.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "kiam.name" . }}
    chart: {{ template "kiam.chart" . }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.serviceAccounts.server.annotations }}
  annotations: {{ toYaml .Values.serviceAccounts.server.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "kiam.serviceAccountName.server" . }}
{{- end }}
{{- end }}
