name: Docker CI [x64]

on:
  push:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        run: |
          docker build -t temp .
          docker inspect temp
