name: Docker Image CI [arm64]

on:
  push:
    branches:
      - "**"

jobs:
  setup-build-publish:
    name: Build and Push Docker image to ECR
    if: github.repository != 'trilogy-group/cn-devflows-function-typescript-skeleton'
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute Tag
        run: |
          SHA=`echo ${GITHUB_SHA} | cut -c1-7`
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/}-${SHA}-arm64 | sed "s/[^[:alnum:]]/-/g")" >> $GITHUB_ENV

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t temp .
          docker inspect temp